[build]
  # Este comando presume que você está usando Vite. 
  # Se usar outra ferramenta, ajuste para o comando de build correspondente (ex: "npm run build").
  command = "vite build"
  publish = "dist" # A pasta onde o resultado do build é salvo.

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
